require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.pluginkeys'
require 'user.run'

require 'conf.lsp-zero'
require 'conf.lspsaga'
require 'conf.lspkind'
require 'conf.nvim-treesitter'
require 'conf.lualine'
require 'conf.telescope'
require 'conf.snippets'
require 'conf.null-ls'
